//AUTHORS
export const ADD_SINGLE_AUTHOR = 'ADD_SINGLE_AUTHOR';
export const DELETE_SINGLE_AUTHOR = 'DELETE_SINGLE_AUTHOR';

//BOOKS
export const ADD_SINGLE_BOOK = 'ADD_SINGLE_BOOK';
export const DELETE_SINGLE_BOOK = 'DELETE_SINGLE_BOOK';
